spring.application.name=conference
spring.datasource.url=jdbc:h2:mem:conferencedb


spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

security.jwt.secret = fromgittogot

server.error.include-message=always

